name: Build & Push Docker Image

on: 
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t test-cicd36 .
      - name: push image
        run: |
          docker login -u noid4589 -p ${{ secrets.DOCKER_HUB_TOK }}
          docker push test-cicd36
